### ISSUE TITLE
Function Type Hint bool

### ISSUE THREAD

**Issue by cracker182** [mtownsend5512/read-time#11]
Hi
Thank you for your work. 
I've encountered a problem with function type-hints bool which can be nullable.

```
Argument 1 passed to Mtownsend\ReadTime\ReadTime::timeOnly() must be of the type boolean, null given
```
I could develop a fix, but the language level needs to raise to php 7.1.x 
Is this an option?

Thank you and have a nice day

**Comment by mtownsend5512** [comment]
Can you give an example as to what is happening? Null should not be passed to the ``timeOnly`` method.

**Comment by cracker182** [comment]
Of course:

```
Routes/web.php

$content = "test test test";

return view('welcome', compact('content'));
```

```
welcome.blade.php

 {{ read_time($content) }}
```
I've not published the config file, since I'm fine with the defaults.

I've found out, that the default config is not loaded properly.

maybe I'm doing wrong. sorry if this is the case.

Greetings

**Comment by mtownsend5512** [comment]
Yeah, the config/language files is required if you're using Laravel.
