### ISSUE TITLE
Potential error in calculation

### ISSUE THREAD

**Issue by assertchris** [mtownsend5512/read-time#13]
First off, thanks for your work here. This is one of those useful little libraries that is just Such A Good Idea™

Now, on to other matters... I think there may be an error in the calculation when it comes to very large bodies of text. In the first example (at about 4.5k words, including code); it calculates the length of time as 15 minutes.

<img width="1109" alt="screenshot 2019-01-20 at 16 21 04" src="https://user-images.githubusercontent.com/200609/51440443-c62a9c00-1ccf-11e9-9570-045a8982a07b.png">

In the second example (at about 6.5k words, including code); it calculates the length of time as 4 minutes.

<img width="1094" alt="screenshot 2019-01-20 at 16 21 13" src="https://user-images.githubusercontent.com/200609/51440451-d9d60280-1ccf-11e9-96a8-373080960d16.png">

Check the size of the scroller, or the lengths of the posts [on the site](https://assertchris.io). You can also check out [where I am using it, on Github](https://github.com/assertchris/assertchris.io/blob/master/app/Model/Post.pre#L154).

**Comment by mtownsend5512** [comment]
Hey Chris!

Thanks for the props.

So, I went onto the article in question, ``"What is this s#*t?!"`` and I went into the inspector and copied all of the HTML content, then loaded it into a file and did a ``file_get_contents`` on it and passed it into a new instance of ReadTime. It gave me a ``36 min read``, which seems more appropriate.

Here is what I suspect may be happening: perhaps not all of your content is being correctly passed into the ReadTime class? One way you can check is by observing the ``words_in_content`` key of the class. To do this, simply do this: ``(new ReadTime($content))->toArray()['words_in_content']``. If you aren't seeing 8370 words for that article, then it's an issue with the content not being appropriately passed into the class.

Let me know what result you get and we can further trouble shoot it.

**Comment by assertchris** [comment]
Thanks for the direction! I'll check it out and let you know.
